use_frameworks!

platform :ios, '10.0'

target 'SomeSupport_Example' do
  pod 'SomeSupport', :path => '../'

  target 'SomeSupport_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase'
  end
end
